export const IpcChannels = {
  search: 'music:search',
  searchStart: 'music:search:start',
  searchCancel: 'music:search:cancel',
  searchResult: 'music:search:result',
  searchDone: 'music:search:done',
  searchError: 'music:search:error',
  getSettings: 'music:settings:get',
  saveSettings: 'music:settings:save',
  pickMusicDirectory: 'music:settings:pick-directory',
  getTracks: 'music:library:list',
  deleteTrack: 'music:library:delete',
  openPath: 'music:fs:open-path',
  showItemInFolder: 'music:fs:show-item-in-folder',
  openTrackFolder: 'music:library:open-folder',
  listAlbums: 'music:albums:list',
  getAlbum: 'music:albums:get',
  createAlbum: 'music:albums:create',
  renameAlbum: 'music:albums:rename',
  deleteAlbum: 'music:albums:delete',
  addTrackToAlbum: 'music:albums:add-track',
  removeTrackFromAlbum: 'music:albums:remove-track',
  enqueueDownload: 'music:download:enqueue',
  listDownloads: 'music:download:list',
  clearDownloads: 'music:download:clear-history',
  cancelDownload: 'music:download:cancel',
  retryDownload: 'music:download:retry',
  downloadProgress: 'music:download:progress',
  libraryChanged: 'music:library:changed',
  getToolStatus: 'music:tools:status',
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
